# Generated by Django 6.0.1 on 2026-02-17 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bookings', models.IntegerField(default=0)),
                ('average_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preferred_location', models.CharField(default='', max_length=100)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=500)),
                ('rating', models.FloatField(default=0.0)),
                ('job_count', models.IntegerField(default=0)),
                ('completed_jobs', models.IntegerField(default=0)),
                ('reliability_score', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('is_new', models.BooleanField(default=True)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avatar', models.CharField(default='https://picsum.photos/100', max_length=200)),
                ('technical_rating', models.FloatField(default=0.0)),
                ('response_time', models.IntegerField(default=0)),
                ('specialization', models.CharField(default='General', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_rating', models.FloatField(blank=True, null=True)),
                ('ai_match_score', models.FloatField(default=0.0)),
                ('estimated_duration', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
